"""update table

Revision ID: 2c57f1f1194e
Revises: bdba3447299b
Create Date: 2023-08-17 14:11:47.802408

"""
from alembic import op
import sqlalchemy_utils
import sqlalchemy as sa
from sqlalchemy import MetaData, Table


# revision identifiers, used by Alembic.
revision = '2c57f1f1194e'
down_revision = 'bdba3447299b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    metadata = MetaData(bind=conn)
    
    # Reflect the appointments table
    appointments_table = Table('appointments', metadata, autoload_with=conn)
    
    # Check if 'slot_id' column exists, if not then add it
    if 'slot_id' not in appointments_table.columns:
        with op.batch_alter_table('appointments', schema=None) as batch_op:
            batch_op.add_column(sa.Column('slot_id', sa.Integer(), nullable=True))
    
    # Check if 'symptoms' column exists, if not then add it
    if 'symptoms' not in appointments_table.columns:
        with op.batch_alter_table('appointments', schema=None) as batch_op:
            batch_op.add_column(sa.Column('symptoms', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('symptoms')
        batch_op.drop_column('slot_id')

    # ### end Alembic commands ###
