"""changes table

Revision ID: 2eaf25dfcb4c
Revises: cd6c451a22de
Create Date: 2021-09-26 18:31:35.461408

"""
from alembic import op
import sqlalchemy_utils
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eaf25dfcb4c'
down_revision = 'cd6c451a22de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centers', sa.Column('speciality', sa.String(length=255), nullable=True))
    op.add_column('centers', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('centers', sa.Column('start', sa.String(length=100), nullable=True))
    op.add_column('centers', sa.Column('end', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('centers', 'end')
    op.drop_column('centers', 'start')
    op.drop_column('centers', 'description')
    op.drop_column('centers', 'speciality')
    # ### end Alembic commands ###
