"""create chat table

Revision ID: 357918b7e751
Revises: 48e38944b620
Create Date: 2021-04-14 07:59:13.542970

"""
from alembic import op
import sqlalchemy_utils
import sqlalchemy as sa
import sqlalchemy_utils
import uuid

# revision identifiers, used by Alembic.
revision = '357918b7e751'
down_revision = '48e38944b620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), default=uuid.uuid4, nullable=False),
    sa.Column('sender', sqlalchemy_utils.types.uuid.UUIDType(), default=uuid.uuid4, nullable=False),
    sa.Column('receiver', sqlalchemy_utils.types.uuid.UUIDType(), default=uuid.uuid4, nullable=False),
    sa.Column('chat_id', sqlalchemy_utils.types.uuid.UUIDType(), default=uuid.uuid4, nullable=False),
    sa.Column('attachement', sa.String(length=255), nullable=True),
    sa.Column('reply_to', sqlalchemy_utils.types.uuid.UUIDType(), default=uuid.uuid4, nullable=True),
    sa.Column('read', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('read_time', sa.DateTime(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_chat_id'), 'chat', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_create_time'), 'chat', ['create_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_create_time'), table_name='chat')
    op.drop_index(op.f('ix_chat_chat_id'), table_name='chat')
    op.drop_table('chat')
    # ### end Alembic commands ###
