"""update

Revision ID: 367d7de8b0be
Revises: 3fe325a02a73
Create Date: 2023-08-26 11:32:36.247852

"""
from alembic import op
import sqlalchemy_utils
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '367d7de8b0be'
down_revision = '3fe325a02a73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
