"""create departments tables

Revision ID: 38911ac74a42
Revises: bdc4689515e5
Create Date: 2021-03-03 09:29:38.289389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38911ac74a42'
down_revision = 'bdc4689515e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('center_department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('center_doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('centers', sa.Column('center_type', sa.String(length=100), server_default='', nullable=True))
    op.add_column('centers', sa.Column('is_approved', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('centers', sa.Column('latitude', sa.String(length=100), nullable=True))
    op.add_column('centers', sa.Column('longitude', sa.String(length=100), nullable=True))
    
    
   
    
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('centers', 'longitude')
    op.drop_column('centers', 'latitude')
    op.drop_column('centers', 'is_approved')
    op.drop_column('centers', 'center_type')
    op.drop_table('center_doctors')
    op.drop_table('center_department')
    op.drop_table('departments')
    # ### end Alembic commands ###
