"""update review table

Revision ID: 91fad7ca90bd
Revises: 2c57f1f1194e
Create Date: 2023-08-20 14:52:47.418701

"""
from alembic import op
import sqlalchemy_utils
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91fad7ca90bd'
down_revision = '2c57f1f1194e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_review', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('patient_review_fk', 'patients', ['patient_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('patient_review_fk', type_='foreignkey')
        batch_op.drop_column('patient_id')
        batch_op.drop_column('patient_review')

    # ### end Alembic commands ###
