"""create invoice table

Revision ID: aeccdbf56877
Revises: cad855d4bd3c
Create Date: 2021-09-26 18:36:42.170319

"""
from alembic import op
import sqlalchemy_utils
import sqlalchemy as sa
import sqlalchemy_utils
import uuid

# revision identifiers, used by Alembic.
revision = 'aeccdbf56877'
down_revision = 'cad855d4bd3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), default=uuid.uuid4, nullable=False),
    sa.Column('status', sa.Enum('none', 'pending', 'cancel', 'error', 'fail', 'success', name='invoicestatusenum'), nullable=True),
    sa.Column('model_type', sa.String(length=255), nullable=True),
    sa.Column('model_id', sa.String(length=255), nullable=True),
    sa.Column('order_id', sa.String(length=255), nullable=True),
    sa.Column('number', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('payer_id', sqlalchemy_utils.types.uuid.UUIDType(), default=uuid.uuid4, nullable=True),
    sa.Column('owner_id', sqlalchemy_utils.types.uuid.UUIDType(), default=uuid.uuid4, nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice')
    # ### end Alembic commands ###
