"""create favorite table

Revision ID: cad855d4bd3c
Revises: 2eaf25dfcb4c
Create Date: 2021-09-26 18:35:41.171760

"""
from alembic import op
import sqlalchemy_utils
import sqlalchemy as sa
import sqlalchemy_utils
import uuid

# revision identifiers, used by Alembic.
revision = 'cad855d4bd3c'
down_revision = '2eaf25dfcb4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), default=uuid.uuid4, nullable=False),
    sa.Column('model_type', sa.String(length=255), nullable=True),
    sa.Column('model_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    # ### end Alembic commands ###
