"""update history

Revision ID: d93f35705bfe
Revises: 367d7de8b0be
Create Date: 2023-08-26 12:13:08.717832

"""
from alembic import op
import sqlalchemy_utils
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd93f35705bfe'
down_revision = '367d7de8b0be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
