"""update db table

Revision ID: dc35f0f022bf
Revises: aeccdbf56877
Create Date: 2022-08-16 11:09:09.332539

"""
from alembic import op
import sqlalchemy_utils
import sqlalchemy as sa
import sqlalchemy_utils
import uuid

# revision identifiers, used by Alembic.
revision = 'dc35f0f022bf'
down_revision = 'aeccdbf56877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('payment_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.alter_column('diagnosis',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True,
               existing_server_default=sa.text("('')"))

    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(precision=16),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('sender',
               existing_type=sa.NUMERIC(precision=16),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('receiver',
               existing_type=sa.NUMERIC(precision=16),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('chat_id',
               existing_type=sa.NUMERIC(precision=16),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('reply_to',
               existing_type=sa.NUMERIC(precision=16),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(precision=16),
               type_=sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4,
               existing_nullable=False)

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(precision=16),
               type_=sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4,
               existing_nullable=False)
        batch_op.alter_column('payer_id',
               existing_type=sa.NUMERIC(precision=16),
               type_=sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4,
               existing_nullable=True)
        batch_op.alter_column('owner_id',
               existing_type=sa.NUMERIC(precision=16),
               type_=sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4,
               existing_nullable=True)

    with op.batch_alter_table('payment_gateway', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('payment_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requester_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('beneficiary', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('beneficiary_id', sa.Integer(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(precision=16),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('transaction_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('payment_status',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('none', 'pending', 'cancel', 'error', 'fail', 'success', 'paid', 'unpaid', 'cancelled', name='paymentstatusenum'),
               existing_nullable=True)
        batch_op.alter_column('payment_gateway',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('payment_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_index('ix_payment_transaction_transaction_id')

    with op.batch_alter_table('payment_type', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_type', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('payment_transaction', schema=None) as batch_op:
        batch_op.create_index('ix_payment_transaction_transaction_id', ['transaction_id'], unique=False)
        batch_op.alter_column('payment_type',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('payment_gateway',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('payment_status',
               existing_type=sa.Enum('none', 'pending', 'cancel', 'error', 'fail', 'success', 'paid', 'unpaid', 'cancelled', name='paymentstatusenum'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=True)
        batch_op.alter_column('transaction_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=255),
               type_=sa.NUMERIC(precision=16),
               existing_nullable=False)
        batch_op.drop_column('beneficiary_id')
        batch_op.drop_column('beneficiary')
        batch_op.drop_column('requester_id')

    with op.batch_alter_table('payment_gateway', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4,
               type_=sa.NUMERIC(precision=16),
               existing_nullable=True)
        batch_op.alter_column('payer_id',
               existing_type=sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4,
               type_=sa.NUMERIC(precision=16),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4,
               type_=sa.NUMERIC(precision=16),
               existing_nullable=False)

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4,
               type_=sa.NUMERIC(precision=16),
               existing_nullable=False)

    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.alter_column('reply_to',
               existing_type=sa.String(length=255),
               type_=sa.NUMERIC(precision=16),
               existing_nullable=True)
        batch_op.alter_column('chat_id',
               existing_type=sa.String(length=255),
               type_=sa.NUMERIC(precision=16),
               existing_nullable=False)
        batch_op.alter_column('receiver',
               existing_type=sa.String(length=255),
               type_=sa.NUMERIC(precision=16),
               existing_nullable=False)
        batch_op.alter_column('sender',
               existing_type=sa.String(length=255),
               type_=sa.NUMERIC(precision=16),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=255),
               type_=sa.NUMERIC(precision=16),
               existing_nullable=False)

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.alter_column('diagnosis',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False,
               existing_server_default=sa.text("('')"))

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('payment_id',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
