"""add column to centers table

Revision ID: e54333109fde
Revises: 66f646e52ee3
Create Date: 2021-03-23 10:53:25.583877

"""
from alembic import op
import sqlalchemy_utils
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e54333109fde'
down_revision = '66f646e52ee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centers', sa.Column('image', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('centers', 'image')
    # ### end Alembic commands ###
